#ifndef _FS_INITRD_BINS_H
#define _FS_INITRD_BINS_H

#include <dunix/types.h>

#define DECLARE_BIN(name) \
    extern const uint8_t bin_##name##_data[]; \
    extern const size_t  bin_##name##_data_len;

DECLARE_BIN(init)
DECLARE_BIN(sh)
DECLARE_BIN(cat)
DECLARE_BIN(ls)
DECLARE_BIN(echo)
DECLARE_BIN(mkdir)
DECLARE_BIN(rm)
DECLARE_BIN(pwd)
DECLARE_BIN(cp)
DECLARE_BIN(ps)
DECLARE_BIN(grep)
DECLARE_BIN(head)
DECLARE_BIN(tail)
DECLARE_BIN(wc)
DECLARE_BIN(find)
DECLARE_BIN(touch)
DECLARE_BIN(chmod)
DECLARE_BIN(chown)
DECLARE_BIN(kill)
DECLARE_BIN(sleep)
DECLARE_BIN(env)
DECLARE_BIN(uname)
DECLARE_BIN(dmesg)
DECLARE_BIN(df)
DECLARE_BIN(mount)
DECLARE_BIN(umount)
DECLARE_BIN(true)
DECLARE_BIN(false)
DECLARE_BIN(login)
DECLARE_BIN(vedit)
DECLARE_BIN(ifconfig)
DECLARE_BIN(ping)
DECLARE_BIN(nc)
DECLARE_BIN(wget)
DECLARE_BIN(httpd)
DECLARE_BIN(cc)
DECLARE_BIN(cal)
DECLARE_BIN(bc)
DECLARE_BIN(xargs)
DECLARE_BIN(which)
DECLARE_BIN(basename)
DECLARE_BIN(dirname)
DECLARE_BIN(neofetch)
DECLARE_BIN(dws)
DECLARE_BIN(dterm)
DECLARE_BIN(dfiles)
DECLARE_BIN(dclock)
DECLARE_BIN(dcalc)
DECLARE_BIN(dsession)
DECLARE_BIN(mkfs)
DECLARE_BIN(installer)
DECLARE_BIN(dinstall)
DECLARE_BIN(linux)
DECLARE_BIN(linux_hello)
DECLARE_BIN(linux_uname)
DECLARE_BIN(links)
DECLARE_BIN(date)
DECLARE_BIN(reboot)
DECLARE_BIN(poweroff)
DECLARE_BIN(clear)
DECLARE_BIN(tee)
DECLARE_BIN(sort)
DECLARE_BIN(uniq)
DECLARE_BIN(tr)
DECLARE_BIN(seq)
DECLARE_BIN(yes)
DECLARE_BIN(more)
DECLARE_BIN(beep)
DECLARE_BIN(du)
DECLARE_BIN(strings)
DECLARE_BIN(hexdump)
DECLARE_BIN(diff)
DECLARE_BIN(cmp)
DECLARE_BIN(uptime)
DECLARE_BIN(sed)
DECLARE_BIN(sudo)
DECLARE_BIN(whoami)
DECLARE_BIN(id)
DECLARE_BIN(dweb)
DECLARE_BIN(browser)
DECLARE_BIN(drm_info)
DECLARE_BIN(glgears)
DECLARE_BIN(snake)
DECLARE_BIN(minesweeper)
DECLARE_BIN(2048)

#undef DECLARE_BIN

void vfs_populate_binaries(void);

#endif /* _FS_INITRD_BINS_H */
