#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
    if (argc < 4) {
        fprintf(stderr, "Usage: %s <symbol_name> <input_file> <output_file>\n", argv[0]);
        return 1;
    }

    const char *sym = argv[1];
    const char *in_path = argv[2];
    const char *out_path = argv[3];

    FILE *fin = fopen(in_path, "rb");
    if (!fin) {
        fprintf(stderr, "Error: cannot open input file %s\n", in_path);
        return 1;
    }

    FILE *fout = fopen(out_path, "w");
    if (!fout) {
        fprintf(stderr, "Error: cannot open output file %s\n", out_path);
        fclose(fin);
        return 1;
    }

    fprintf(fout, "/* Auto-generated by bin2c from %s */\n", in_path);
    fprintf(fout, "#if defined(__has_include)\n");
    fprintf(fout, "  #if __has_include(<dunix/types.h>)\n");
    fprintf(fout, "    #include <dunix/types.h>\n");
    fprintf(fout, "  #else\n");
    fprintf(fout, "    #include <stdint.h>\n");
    fprintf(fout, "    #include <stddef.h>\n");
    fprintf(fout, "  #endif\n");
    fprintf(fout, "#else\n");
    fprintf(fout, "  #include <stdint.h>\n");
    fprintf(fout, "  #include <stddef.h>\n");
    fprintf(fout, "#endif\n\n");
    fprintf(fout, "const uint8_t %s[] __attribute__((aligned(16))) = {\n", sym);

    unsigned char buf[1024];
    size_t n;
    size_t total = 0;
    int col = 0;

    while ((n = fread(buf, 1, sizeof(buf), fin)) > 0) {
        for (size_t i = 0; i < n; i++) {
            fprintf(fout, "0x%02x, ", buf[i]);
            total++;
            col++;
            if (col >= 16) {
                fprintf(fout, "\n");
                col = 0;
            }
        }
    }

    if (col > 0) {
        fprintf(fout, "\n");
    }

    fprintf(fout, "};\n\n");
    fprintf(fout, "const size_t %s_len = %zu;\n", sym, total);

    fclose(fin);
    fclose(fout);
    return 0;
}
